/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HarmoniesRouteImport } from './routes/harmonies'
import { Route as PalettesRouteImport } from './routes/palettes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HarmoniesRoute = HarmoniesRouteImport.update({
  id: '/harmonies',
  path: '/harmonies',
  getParentRoute: () => rootRouteImport,
} as any)
const PalettesRoute = PalettesRouteImport.update({
  id: '/palettes',
  path: '/palettes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/harmonies': typeof HarmoniesRoute
  '/palettes': typeof PalettesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/harmonies': typeof HarmoniesRoute
  '/palettes': typeof PalettesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/harmonies': typeof HarmoniesRoute
  '/palettes': typeof PalettesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/harmonies' | '/palettes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/harmonies' | '/palettes'
  id: '__root__' | '/' | '/harmonies' | '/palettes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HarmoniesRoute: typeof HarmoniesRoute
  PalettesRoute: typeof PalettesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harmonies': {
      id: '/harmonies'
      path: '/harmonies'
      fullPath: '/harmonies'
      preLoaderRoute: typeof HarmoniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palettes': {
      id: '/palettes'
      path: '/palettes'
      fullPath: '/palettes'
      preLoaderRoute: typeof PalettesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HarmoniesRoute: HarmoniesRoute,
  PalettesRoute: PalettesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
